### Crear proyecto base

npm create vite@latest vizzuality-dashboard -- --template react-ts
cd vizzuality-dashboard
npm install
npm run dev


### Instalar dependencias clave

Tailwind
https://tailwindcss.com/docs/installation/using-vite


Configurar ESLint + Prettier
npm install -D eslint prettier eslint-config-prettier


### Estructura del proyecto
src/
 ├─ components/
 │   ├─ ui/
 │   └─ layout/
 ├─ pages/
 │   └─ Dashboard.tsx
 ├─ hooks/
 │   └─ useFetch.ts
 ├─ services/
 │   └─ api.ts
 ├─ types/
 │   └─ index.ts
 ├─ utils/
 ├─ App.tsx
 └─ main.tsx


### Integrar api

https://docs.openaq.org/ ---> pswd account: "ME#j8ssGc9#P8EW" // API Key ---> "3a08df6f2bebafe04c03e7f299a0022e85fe1a148bf6fb54608b50d951e87b67"

1. Buscar una Location (estación)
2. Pedir su Latest (últimas mediciones)
3. Renderizar en UI con loading/error/empty

*** Crear openaq.ts en services para centralizar la comunicación con la API (evitar fetch por todo el proyecto), añadir los headers que necesita OpenAQ, describir la forma de los datos ****



### Componente Dashboard

Qué problema resuelve ---> el usuario escribe un Location ID y pide a OpenAQ: 
    - datos de la ubicación
    - últimas mediciones
    Muestra: 
    - mientras carga: "Loading..."
    - si fallta: error
    - si va bien: nombre de la estación + lista de mediciones


### Mini server para gestionar CORS 
instalar dotenv
express
cors